export const ACTION_CHANGE_STOPS = "ACTION_CHANGE_STOPS";
export const ACTION_CHANGE_CURRENCY = "ACTION_CHANGE_CURRENCY";
export const ACTION_FASTER_OR_CHEAPER = "ACTION_FASTER_OR_CHEAPER";
export const ACTION_RECEIVED_TICKETS = "ACTION_RECEIVED_TICKETS";

export const ACTION_TICKETS_HAS_ERRORED = "ACTION_TICKETS_HAS_ERRORED";
export const ACTION_TICKETS_IS_LOADING = "ACTION_TICKETS_IS_LOADING";
export const ACTION_TICKETS_FETCH_DATA_SUCCESS =
  "ACTION_TICKETS_FETCH_DATA_SUCCESS";

export const ACTION_CURRENCY_RATES_HAS_ERRORED =
  "ACTION_CURRENCY_RATES_HAS_ERRORED";
export const ACTION_CURRENCY_RATES_IS_LOADING =
  "ACTION_CURRENCY_RATES_IS_LOADING";
export const ACTION_CURRENCY_RATES_FETCH_DATA_SUCCESS =
  "ACTION_CURRENCY_RATES_FETCH_DATA_SUCCESS";
